### ISSUE TITLE
How to pass in tortoise_autoplay

### ISSUE THREAD

**Issue by noorbeast** [JarodMica/Vivy#14]
I have tortoise installed and running. When I start the tortoise branch of Vivy it says: If valid Tortoise TTS installation, make sure to pass in tortoise_autoplay.

How do I do I pass in tortoise_autoplay?

**Comment by JarodMica** [comment]
This branch is still a bit experimental and that warning message is actually a bit unlcear/incorrect now that I look at it.  I'll have to modify it to print out the exception so that I can get a better idea on what's happening.  When I get the time to do this, I'll let you know.

In the mean time, could you post the code that you're trying to run?

**Comment by noorbeast** [comment]
I was just trying to start the supplied assistant and chat files.

**Comment by JarodMica** [comment]
New code on the repo now, try pulling the repo with the latest updates and then rerunning
